// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAWSqnPRXpdqxmiQiJinyIWkKhrFAPqw',
    appId: '1:694151618700:web:4d76d0949b7af5af851ba9',
    messagingSenderId: '694151618700',
    projectId: 'ai-tour-guide-98294',
    authDomain: 'ai-tour-guide-98294.firebaseapp.com',
    storageBucket: 'ai-tour-guide-98294.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZh0wj-947ZuU76Rx2j4PaoiSXc5sTowI',
    appId: '1:694151618700:android:3661494931118134851ba9',
    messagingSenderId: '694151618700',
    projectId: 'ai-tour-guide-98294',
    storageBucket: 'ai-tour-guide-98294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkR0iAZZRKdvAqaA-9KWNdyJ1M2B_2sn8',
    appId: '1:694151618700:ios:64bc2ed6a8aab64c851ba9',
    messagingSenderId: '694151618700',
    projectId: 'ai-tour-guide-98294',
    storageBucket: 'ai-tour-guide-98294.firebasestorage.app',
    iosBundleId: 'com.example.aiTourGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkR0iAZZRKdvAqaA-9KWNdyJ1M2B_2sn8',
    appId: '1:694151618700:ios:64bc2ed6a8aab64c851ba9',
    messagingSenderId: '694151618700',
    projectId: 'ai-tour-guide-98294',
    storageBucket: 'ai-tour-guide-98294.firebasestorage.app',
    iosBundleId: 'com.example.aiTourGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAWSqnPRXpdqxmiQiJinyIWkKhrFAPqw',
    appId: '1:694151618700:web:f0dcb13bb72563c6851ba9',
    messagingSenderId: '694151618700',
    projectId: 'ai-tour-guide-98294',
    authDomain: 'ai-tour-guide-98294.firebaseapp.com',
    storageBucket: 'ai-tour-guide-98294.firebasestorage.app',
  );
}
